### ISSUE TITLE
Give the debug mini controls an id

### ISSUE THREAD

**Issue by layflags** [gren-lang/browser#1]
What always bothers me during development is that I need to reposition the debug mini controls, because I placed some button in the bottom right corner. To do so I use a CSS selector like `div[style^="position: fixed; bottom: 2em; right: 2em;"]` which looks horrible. So let's give it an `id` like e.g. `gren-debugger-mini-controls` 🙏

https://github.com/gren-lang/browser/blob/main/src/Debugger/Overlay.gren#L478

**Comment by passiomatic** [comment]
If three's a concrete possibility to have _multiple_ Gren apps in a page I would use a CSS class instead. Anyway, coming from Elm at this point anything is better than nothing.  😅

**Comment by layflags** [comment]
True @passiomatic, that would be even better for styling! Since there are already some fix `id`s used, I thought let's keep using `id`s ... but they are probably used for referencing the nodes somewhere?!
- https://github.com/gren-lang/browser/blob/main/src/Debugger/Overlay.gren#L159
- https://github.com/gren-lang/browser/blob/main/src/Debugger/Overlay.gren#L239

**Comment by robinheghan** [comment]
I agree that this would be nice to have, but don't have the time to persue this right now.

A PR would be welcome! If you need help in how to test an in-dev version, send me a message on zulip

**Comment by layflags** [comment]
Thank you for this improvement @robinheghan 🙏
